apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result-dev
  name: result-dev
  selfLink: /api/v1/namespaces//services/result-dev
spec:
  clusterIP: 
  ports:
  - name: 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: result
  sessionAffinity: None
  type: ClusterIP
status: